const path = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    path.join(__dirname, './pages/**/*.{js,ts,jsx,tsx,mdx}'),
    path.join(__dirname, './components/**/*.{js,ts,jsx,tsx,mdx}'),
    path.join(__dirname, './app/**/*.{js,ts,jsx,tsx,mdx}'),
  ],
  safelist: [
    'min-h-screen', 'flex', 'flex-col', 'flex-1', 'flex-shrink-0',
    'items-center', 'items-start', 'items-end',
    'justify-center', 'justify-between', 'justify-start', 'justify-end',
    'gap-1', 'gap-2', 'gap-3', 'gap-4', 'gap-6', 'gap-8',
    'space-y-1', 'space-y-2', 'space-y-3', 'space-y-4', 'space-y-6',
    'space-x-2', 'space-x-3', 'space-x-4',
    'p-1', 'p-2', 'p-3', 'p-4', 'p-6', 'p-8',
    'px-2', 'px-3', 'px-4', 'px-6', 'px-8',
    'py-1', 'py-2', 'py-3', 'py-4', 'py-6',
    'pt-1', 'pt-2', 'pt-4', 'pt-6', 'pb-2', 'pb-4', 'pb-6',
    'pl-3', 'pl-4', 'pl-10', 'pr-3', 'pr-4', 'pr-10',
    'm-0', 'm-1', 'm-2', 'm-4',
    'mb-1', 'mb-2', 'mb-3', 'mb-4', 'mb-6', 'mb-8',
    'mt-1', 'mt-2', 'mt-4', 'mt-6', 'ml-auto', 'mr-auto',
    'w-full', 'w-auto', 'w-5', 'w-6', 'w-8', 'w-10', 'w-12', 'w-16', 'w-64', 'w-80',
    'h-full', 'h-5', 'h-6', 'h-8', 'h-10', 'h-12', 'h-16', 'h-screen',
    'max-w-xs', 'max-w-sm', 'max-w-md', 'max-w-lg', 'max-w-xl', 'max-w-2xl', 'max-w-7xl',
    'min-w-0', 'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl',
    'font-normal', 'font-medium', 'font-semibold', 'font-bold',
    'text-white', 'text-black',
    'text-slate-300', 'text-slate-400', 'text-slate-500', 'text-slate-600', 'text-slate-700', 'text-slate-900',
    'text-gray-400', 'text-gray-500', 'text-gray-700', 'text-gray-900',
    'text-red-500', 'text-red-600', 'text-green-500', 'text-green-600', 'text-yellow-500', 'text-blue-500', 'text-blue-600',
    'bg-white', 'bg-black', 'bg-transparent',
    'bg-slate-50', 'bg-slate-100', 'bg-slate-200', 'bg-slate-700', 'bg-slate-800', 'bg-slate-900',
    'bg-gray-50', 'bg-gray-100', 'bg-gray-200',
    'bg-red-50', 'bg-red-100', 'bg-red-500', 'bg-red-600',
    'bg-green-50', 'bg-green-100', 'bg-green-500', 'bg-green-600',
    'bg-yellow-50', 'bg-yellow-100', 'bg-yellow-500',
    'bg-blue-50', 'bg-blue-100', 'bg-blue-500', 'bg-blue-600',
    'bg-gradient-to-br', 'bg-gradient-to-r', 'bg-gradient-to-b',
    'from-af-navy', 'via-af-blue', 'to-af-mid',
    'bg-af-navy', 'bg-af-blue', 'bg-af-mid', 'bg-af-accent', 'bg-af-light', 'bg-af-border',
    'text-af-navy', 'text-af-blue', 'text-af-mid', 'text-af-accent',
    'border-af-border', 'border-af-accent', 'hover:bg-af-mid', 'hover:bg-af-accent',
    'bg-white/10', 'bg-white/20', 'bg-black/10', 'bg-black/20', 'bg-black/50',
    'border', 'border-2', 'border-t', 'border-b', 'border-l', 'border-r',
    'border-gray-100', 'border-gray-200', 'border-gray-300',
    'border-slate-200', 'border-slate-300',
    'rounded', 'rounded-sm', 'rounded-md', 'rounded-lg', 'rounded-xl', 'rounded-2xl', 'rounded-full',
    'shadow', 'shadow-sm', 'shadow-md', 'shadow-lg', 'shadow-xl', 'shadow-2xl',
    'ring-1', 'ring-2', 'ring-af-accent',
    'focus:outline-none', 'focus:ring-2', 'focus:ring-af-accent', 'focus:border-af-accent',
    'hover:bg-slate-50', 'hover:bg-slate-700', 'hover:bg-gray-50',
    'hover:text-white', 'hover:text-af-accent',
    'cursor-pointer', 'cursor-grab', 'cursor-grabbing',
    'overflow-hidden', 'overflow-y-auto', 'overflow-x-auto', 'overflow-x-hidden',
    'relative', 'absolute', 'fixed', 'sticky',
    'inset-0', 'inset-y-0', 'top-0', 'right-0', 'bottom-0', 'left-0',
    'z-10', 'z-20', 'z-50',
    'grid', 'grid-cols-1', 'grid-cols-2', 'grid-cols-3', 'grid-cols-4',
    'col-span-1', 'col-span-2', 'col-span-3', 'col-span-4',
    'block', 'inline-block', 'inline', 'inline-flex', 'hidden',
    'truncate', 'whitespace-nowrap', 'break-all',
    'select-none', 'pointer-events-none',
    'opacity-0', 'opacity-50', 'opacity-100',
    'transition', 'transition-all', 'transition-colors', 'transition-opacity',
    'duration-150', 'duration-200', 'duration-300',
    'text-center', 'text-left', 'text-right',
    'leading-tight', 'leading-normal', 'leading-relaxed',
    'list-none', 'disabled:opacity-50', 'disabled:cursor-not-allowed',
    'sm:grid-cols-2', 'sm:grid-cols-3', 'sm:grid-cols-4',
    'lg:grid-cols-3', 'lg:grid-cols-4', 'md:flex', 'md:hidden', 'resize-none',
  ],
  theme: {
    extend: {
      colors: {
        'af-navy': '#0d2545',
        'af-blue': '#1a3f6f',
        'af-mid': '#2261a8',
        'af-accent': '#3b82c4',
        'af-light': '#e8f0f9',
        'af-border': '#c5d6eb',
      },
    },
  },
  plugins: [],
};
